package pt.ulisboa.tecnico.sdis.store.ws.it;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.List;

import org.junit.*;

// classes generated by wsimport from WSDL
import pt.ulisboa.tecnico.sdis.store.ws.*;


/**
 * Integration Test suite
 */
public class ListDocsIT extends AbstractStoreIT {

    // tests
    // assertEquals(expected, actual);

    // public List<String> listDocs(String userId) throws
    // UserDoesNotExist_Exception

    @Test(expected = UserDoesNotExist_Exception.class)
    public void testListDocsNoUser() throws Exception {
        final String user = "userthatdoesnotexist";
        STORE_CLIENT.listDocs(user);
    }

    @Test(expected = UserDoesNotExist_Exception.class)
    public void testListDocsNullUser() throws Exception {
        STORE_CLIENT.listDocs(null);
    }

    @Test(expected = UserDoesNotExist_Exception.class)
    public void testListDocsEmptyUser() throws Exception {
        final String user = "";
        STORE_CLIENT.listDocs(user);
    }

    @Test
    public void testEmptyListDocs() throws Exception {
        final String user = "bruno";

        List<String> list = STORE_CLIENT.listDocs(user);
        assertNotNull(list);
        assertEquals(0, list.size());
    }

    @Test
    public void testListDocs() throws Exception {
        final String user = "bruno";

        {
            final DocUserPair docUser = new DocUserPair();
            docUser.setDocumentId("b1");
            docUser.setUserId(user);

            STORE_CLIENT.createDoc(docUser);
        }
        {
            final DocUserPair docUser = new DocUserPair();
            docUser.setDocumentId("b2");
            docUser.setUserId(user);

            STORE_CLIENT.createDoc(docUser);
        }
        {
            final DocUserPair docUser = new DocUserPair();
            docUser.setDocumentId("b3");
            docUser.setUserId(user);

            STORE_CLIENT.createDoc(docUser);
        }

        List<String> list = STORE_CLIENT.listDocs(user);
        assertNotNull(list);
        assertEquals(3, list.size());
        assertTrue(list.contains("b1"));
        assertTrue(list.contains("b2"));
        assertTrue(list.contains("b3"));
    }

}
